- id: terraform-docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: bin/terraform-docs.sh
  args: [--args=--with-aggregate-type-defaults]
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform-validate
  name: Terraform validate
  description: Validates all Terraform configuration files.
  entry: bin/terraform-validate.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform-sec
  name: Terraform validate with tfsec
  description: Static analysis of Terraform templates to spot potential security issues.
  entry: bin/terraform-sec.sh
  language: script

- id: terraform-lint
  name: Terraform validate with tflint
  description: Validates all Terraform configuration files with TFLint.
  entry: bin/terraform-lint.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: bin/terraform-fmt.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: checkov
  name: Checkov
  description: Runs checkov on Terraform templates.
  entry: checkov -d .
  language: python
  pass_filenames: false
  always_run: false
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: helm-lint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: bin/helm-lint.sh
  language: script
  files: \.((ya?ml)|(tpl))$

- id: helm-unittest
  name: Helm-unittest
  description: This hook run helm unittest from quintush/helm-unittest
  entry: bin/helm-unittest.sh
  language: script
  pass_filenames: false
  always_run: true

- id: ansible-lint
  name: Ansible-lint
  description: This hook runs ansible-lint.
  entry: ansible-lint --force-color
  language: python
  pass_filenames: false
  always_run: true

- id: hado-lint
  name: Lint Dockerfiles
  description: Runs hadolint to lint Dockerfiles
  language: script
  entry: bin/docker-lint.sh
  files: Dockerfil*
