- id: terraform-docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: bin/terraform_docs.sh
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform-validate
  name: Terraform validate
  description: Validates all Terraform configuration files.
  entry: bin/terraform_validate.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform-sec
  name: Terraform validate with tfsec
  description: Static analysis of Terraform templates to spot potential security issues.
  entry: bin/terraform_tfsec.sh
  language: script

- id: terraform-lint
  name: Terraform validate with tflint
  description: Validates all Terraform configuration files with TFLint.
  entry: bin/terraform_tflint.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: bin/terraform_fmt.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: checkov
  name: Checkov
  description: Runs checkov on Terraform templates.
  entry: checkov -d .
  language: python
  pass_filenames: false
  always_run: false
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: helm-lint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: bin/helmlint.sh
  language: script
  files: \.((ya?ml)|(tpl))$

- id: helm-unittest
  name: Helm-unittest
  description: This hook run helm unittest from quintush/helm-unittest
  entry: bin/helm-unittest.sh
  language: script
  pass_filenames: false
  always_run: true

- id: docker-lint
  name: Lint Dockerfiles
  description: Runs hadolint to lint Dockerfiles
  language: script
  entry: bin/docker-lint.sh
  files: Dockerfil*

- id: shellcheck
  name: Shellcheck Bash Linter
  description: Performs linting on bash scripts
  entry: bin/shellcheck.sh
  language: script

- id: verify-json
  name: Pretty Print JSON files
  description: Checks JSON files and pretty prints them
  entry: bin/verify-json.sh
  language: script
  files: \.json$

- id: verify-yaml
  name: Pretty Print YAML files
  description: Checks YAML files and pretty prints them
  entry: bin/verify-yaml.sh
  language: script
  files: \.(ya?ml)$

- id: markdown-toc
  name: Generate Markdown toc
  description: Generate a Table of Contents in a Markdown Document
  entry: bin/markdown-toc.sh
  language: script
  files: \.md$

- id: no-commit-on-branch
  name: No commit on master or main
  description: Do no allow any commit on either specified branch.
  entry: bin/no-commit-on-branch.sh
  language: script
  always_run: true
