# This will execute some scripts on main branch.

name: MasterRun

on:
  push:
    branches:
    - master
    - main

  workflow_dispatch:

jobs:
  runme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - name: Checkout dj-wasabi-release repo
      uses: actions/checkout@v2
      with:
        repository: dj-wasabi/dj-wasabi-release
        path: dj-wasabi-release

    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: main

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install some packages
      run: |
        pip install wheel requests pyyaml

    - name: Commit Changelog file
      run: |
        # We are cloned in the 'main' directory and the dj-wasabi-release
        # repository is the 'dj-wasabi-release' next to 'main'
        cd main
        git config --get remote.origin.url

        # Generate CHANGELOG.md file
        ../dj-wasabi-release/release.py -d

        # Let commit the changes if there are any? (Well there should be!)
        if [[ $(git status | grep -c 'CHANGELOG.md' || true) -gt 0 ]]
          then  echo "Committing file"
                git config --global user.name 'Werner Dijkerman [GH bot]'
                git config --global user.email 'github@dj-wasabi.nl'

                git add CHANGELOG.md
                git commit -m "Updated CHANGELOG.md on \"$(date "+%Y-%m-%d %H:%M:%S")\"" CHANGELOG.md
                git push
        fi
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
